package hitachi_genai.popDashBoard.enums;

public enum ServiceName {
    API_MANAGEMENT, APP_CONFIGURATION, AZURE_AI_SERVICES, AZURE_APP_SERVICE, AZURE_CONTAINER_REGISTRY,AZURE_KUBERNETES_SERVICE,AZURE_MARKETPLACE, AZURE_MONITOR, AZURE_PRIVATE_LINK, KEY_VAULT, LOAD_BALANCER, NETWORK_WATCHER,STORAGE_ACCOUNT, VIRTUAL_MACHINES, VIRTUAL_MACHINE_SCALE_SET,VIRTUAL_NETWORK
}
